{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "debug-shell.serviceAccountName" . }}
  namespace: {{ .Values.pod.namespace | default .Release.Namespace }}
  labels:
    {{- include "debug-shell.labels" . | nindent 4 }}
{{- end }}
